<?php

	namespace app\odc\admin;

	use app\admin\controller\Admin;
	use app\odc\model\RegionModel;
	use app\odc\model\RegionUserModel;

	class BaseController extends Admin
	{
		protected $user = [];

		public function _initialize()
		{
			parent::_initialize(); // TODO: Change the autogenerated stub
			$this->user = session('user_auth');

			$this->user['type'] = RegionUserModel::where(['user_id' => $this->user['uid']])->column('type')[0];
			$this->user['region_id'] = RegionUserModel::where(['user_id' => $this->user['uid']])->column('region_id')[0];

			if ($Region = RegionModel::where(['id' => $this->user['region_id']])->column('region_name'))
			{
				$this->user['region_name'] = $Region[0];
			}
			$this->user['All']=' ';
			foreach ($this->user as $key => $item)
			{
				$this->user['All'] .= "< {$key}:{$item} ><br>";
			}
		}

		static public function userlist($type = false)
		{
			$where = [];
			if ($type == 'mg')
			{
				$where['type'] = 1;
			} else if ($type == 'user')
			{
				$where['type'] = 0;
			}

			return RegionUserModel::where($where)
				->field('admin_user.id,admin_user.username')
				->join('admin_user', 'admin_user.id = dp_odc_user.user_id')
				->column('admin_user.id,admin_user.username');
		}

		public function CheckAdmin()
		{
			return $this->user['uid'] == 1 ? true : false;
		}

		public function CheckManager()
		{
			return $this->user['type'] == 1 ? true : false;
		}



	}