<?php

	return [
		[
			'title'       => 'ODC',
			'icon'        => 'fa fa-fw fa-newspaper-o',
			'url_type'    => 'module_admin',
			'url_value'   => 'odc/index/index',
			'url_target'  => '_self',
			'online_hide' => 0,
			'sort'        => 100,
			'child'       => [
				[
					'title'       => 'ODC_Manager',
					'icon'        => 'fa fa-fw fa-folder-open-o',
					'url_type'    => 'module_admin',
					'url_value'   => '',
					'url_target'  => '_self',
					'online_hide' => 0,
					'sort'        => 100,
					'child'       => [
						[
							'title'       => 'Address',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/mg_address/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_address/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_address/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_address/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],

							],
						],
						[
							'title'       => 'User',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/mg_user/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_user/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_user/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_user/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],

							],
						],
						[
							'title'       => 'Region',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/mg_region/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_region/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_region/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_region/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],

							],
						],
						[
							'title'       => 'Category',
							'icon'        => 'fa fa-fw fa-recycle',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/mg_category/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_category/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_category/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_category/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
							],
						],
						[
							'title'       => 'Product',
							'icon'        => 'fa fa-fw fa-file-word-o',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/mg_product/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_product/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_product/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_product/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
							],
						],

						[
							'title'       => 'Inventory',
							'icon'        => 'fa fa-fw fa-recycle',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/mg_inventory/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_inventory/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_inventory/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/mg_inventory/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
							],
						],
					],
				],
				[
					'title'       => 'ODC_User',
					'icon'        => 'fa fa-fw fa-folder-open-o',
					'url_type'    => 'module_admin',
					'url_value'   => '',
					'url_target'  => '_self',
					'online_hide' => 0,
					'sort'        => 100,
					'child'       => [
						[
							'title'       => 'Address',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/u_address/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_address/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_address/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_address/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],

							],
						],

						[
							'title'       => 'Category',
							'icon'        => 'fa fa-fw fa-recycle',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/u_category/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_category/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_category/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_category/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
							],
						],
						[
							'title'       => 'Product',
							'icon'        => 'fa fa-fw fa-file-word-o',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/u_product/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_product/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_product/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_product/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
							],
						],

						[
							'title'       => 'Inventory',
							'icon'        => 'fa fa-fw fa-recycle',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/u_inventory/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_inventory/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_inventory/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/u_inventory/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
							],
						],
					],
				],
				[
					'title'       => 'ODC_Market',
					'icon'        => 'fa fa-fw fa-folder-open-o',
					'url_type'    => 'module_admin',
					'url_value'   => '',
					'url_target'  => '_self',
					'online_hide' => 0,
					'sort'        => 100,
					'child'       => [
						[
							'title'       => 'market',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/market/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
							'child'       => [
								[
									'title'       => 'Create',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/market/add',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Edit',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/market/edit',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],
								[
									'title'       => 'Delete',
									'icon'        => '',
									'url_type'    => 'module_admin',
									'url_value'   => 'odc/market/delete',
									'url_target'  => '_self',
									'online_hide' => 0,
									'sort'        => 100,
								],

							],
						],
						[
							'title'       => 'Buyer Order',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/buyer_order/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
						],
						[
							'title'       => 'Supplier Order',
							'icon'        => 'fa fa-fw fa-list',
							'url_type'    => 'module_admin',
							'url_value'   => 'odc/supplier_order/index',
							'url_target'  => '_self',
							'online_hide' => 0,
							'sort'        => 100,
						],


					],
				],
			],
		],
	];
